### ISSUE TITLE
[Core] make crud product

### ISSUE THREAD

**Issue by pho0m** [Utotech-organize/com-edu-reuion-core#39]
create crud in core server with validator

**Comment by pho0m** [comment]
ผมเพิ่มแล้วครับ อันนี้เป็น router
![Image](https://github.com/Utotech-organize/com-edu-reuion-core/assets/65944965/26e09aac-44f8-4c68-9ccb-96e9c57ae79a)

แล้วก็อันนี้คือ ผลลัพธ์
![Image](https://github.com/Utotech-organize/com-edu-reuion-core/assets/65944965/b9d92009-042d-4710-b2b7-83ac5a16dc8c)

**Comment by Nathanon58** [comment]
โอเคครับ เรียบร้อยครับ

**Comment by pho0m** [comment]
โอเครรร สวยเก่งมากครับ
